import { useState } from 'react'
import { Moon, Sun, LayoutGrid, Folder as FolderIcon, Plus, Search as SearchIcon } from 'lucide-react'
import BookmarkCard from '../components/BookmarkCard'
import BookmarkRow from '../components/BookmarkRow'
import FolderCard from '../components/FolderCard'
import TopicsBox from '../components/TopicsBox'
import { Bookmark, Folder } from '../lib/api'

const now = new Date().toISOString()

const bookmarks: Bookmark[] = [
  {
    id: 'mock-1',
    url: 'https://linear.app/blog/scaling-product-work',
    domain: 'linear.app',
    original_title: 'Scaling product work without losing craft',
    clean_title: 'Scaling product work without losing craft',
    ai_summary: 'A practical essay on keeping product teams focused, intentional, and fast as the surface area grows.',
    raw_notes: null,
    auto_tags: ['product', 'workflow', 'teams'],
    favicon_url: 'https://www.google.com/s2/favicons?domain=linear.app&sz=64',
    thumbnail_url: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80',
    content_type: 'article', intent_type: 'reference', technical_level: null, key_quotes: [],
    created_at: now, updated_at: now, last_accessed_at: null, access_count: 0,
    enrichment_status: 'completed', enrichment_error: null,
    is_public: true, folder_id: null, suggested_folder_name: null,
  },
  {
    id: 'mock-2',
    url: 'https://www.are.na/editorial',
    domain: 'are.na',
    original_title: 'A calmer way to collect references',
    clean_title: 'A calmer way to collect references',
    ai_summary: 'A visual reference for personal libraries that feel collected over time rather than generated by an assistant.',
    raw_notes: null,
    auto_tags: ['design', 'reference', 'library'],
    favicon_url: 'https://www.google.com/s2/favicons?domain=are.na&sz=64',
    thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    content_type: 'article', intent_type: 'inspiration', technical_level: null, key_quotes: [],
    created_at: '2026-05-15T10:00:00.000Z', updated_at: now, last_accessed_at: null, access_count: 0,
    enrichment_status: 'completed', enrichment_error: null,
    is_public: false, folder_id: null, suggested_folder_name: null,
  },
  {
    id: 'mock-3',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/container_queries',
    domain: 'developer.mozilla.org',
    original_title: 'CSS container queries',
    clean_title: 'CSS container queries',
    ai_summary: 'MDN reference covering responsive components that adapt to their container instead of the viewport.',
    raw_notes: null,
    auto_tags: ['css', 'frontend', 'reference', 'layout'],
    favicon_url: 'https://www.google.com/s2/favicons?domain=developer.mozilla.org&sz=64',
    thumbnail_url: null,
    content_type: 'documentation', intent_type: 'learn', technical_level: 'intermediate', key_quotes: [],
    created_at: '2026-05-10T10:00:00.000Z', updated_at: now, last_accessed_at: null, access_count: 0,
    enrichment_status: 'completed', enrichment_error: null,
    is_public: true, folder_id: null, suggested_folder_name: null,
  },
]

const folders: Folder[] = [
  { id: 'f1', user_id: 'u', name: 'Reading list', icon: null, color: null, created_at: now, updated_at: now, bookmark_count: 24 },
  { id: 'f2', user_id: 'u', name: 'Design references', icon: null, color: null, created_at: now, updated_at: now, bookmark_count: 7 },
  { id: 'f3', user_id: 'u', name: 'Tooling', icon: null, color: null, created_at: now, updated_at: now, bookmark_count: 1 },
  { id: 'f4', user_id: 'u', name: 'Archive', icon: null, color: null, created_at: now, updated_at: now, bookmark_count: 0 },
]

const topics = [
  { tag: 'design', count: 14 },
  { tag: 'product', count: 11 },
  { tag: 'frontend', count: 9 },
  { tag: 'workflow', count: 7 },
  { tag: 'css', count: 6 },
  { tag: 'reference', count: 5 },
  { tag: 'ai', count: 3 },
  { tag: 'reading', count: 2 },
]

export default function CardRedesignMock() {
  const [dark, setDark] = useState(false)
  const [selectedTags, setSelectedTags] = useState<string[]>(['design'])
  const [selectedFolder, setSelectedFolder] = useState<string | null>('f1')

  const toggleTag = (tag: string) => setSelectedTags(prev =>
    prev.includes(tag) ? prev.filter(t => t !== tag) : [...prev, tag]
  )

  const sidebarItem = 'w-full flex items-center gap-3 px-3 py-2 rounded-2xl text-sm font-medium transition-colors cursor-pointer'
  const sidebarActive = 'bg-white text-slate-950 ring-1 ring-slate-200 shadow-sm dark:bg-slate-800 dark:text-slate-50 dark:ring-slate-700'
  const sidebarIdle = 'text-slate-600 hover:bg-white/60 hover:text-slate-900 dark:text-slate-400 dark:hover:bg-slate-900 dark:hover:text-slate-100'

  return (
    <div className={dark ? 'dark' : ''}>
      <main className="min-h-screen bg-[#eef1ee] text-slate-950 transition-colors dark:bg-[#0b0d11] dark:text-slate-100">
        {/* Mock header */}
        <header className="sticky top-0 z-40 border-b border-slate-200/70 bg-[#eef1ee]/80 backdrop-blur-md dark:border-slate-800/80 dark:bg-[#0b0d11]/80">
          <div className="mx-auto flex h-16 max-w-screen-2xl items-center gap-4 px-6">
            <div className="flex items-center gap-2">
              <span className="font-display text-2xl text-slate-950 dark:text-slate-50">markly</span>
            </div>
            <div className="relative mx-auto w-full max-w-xl">
              <SearchIcon className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
              <input
                placeholder="Search your bookmarks..."
                className="w-full rounded-full border border-slate-200 bg-white px-12 py-2 text-sm text-slate-900 placeholder-slate-400 focus:border-slate-400 focus:ring-2 focus:ring-slate-100 dark:border-slate-700 dark:bg-slate-900 dark:text-white dark:placeholder-slate-500"
              />
            </div>
            <button className="flex items-center gap-2 rounded-full bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 dark:bg-slate-100 dark:text-slate-950 dark:hover:bg-white">
              <Plus className="h-4 w-4" /> Add
            </button>
            <button
              onClick={() => setDark(d => !d)}
              className="flex items-center gap-2 rounded-full border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"
            >
              {dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
              {dark ? 'Light' : 'Dark'}
            </button>
          </div>
        </header>

        <div className="mx-auto flex max-w-screen-2xl gap-6 px-6 py-8">
          {/* Mock sidebar */}
          <aside className="hidden w-60 shrink-0 space-y-4 lg:block">
            <div className="space-y-1">
              <button
                onClick={() => setSelectedFolder(null)}
                className={`${sidebarItem} ${selectedFolder === null ? sidebarActive : sidebarIdle}`}
              >
                <LayoutGrid className="h-4 w-4" /> Everything
              </button>
            </div>
            <div>
              <p className="mb-2 px-3 text-xs font-medium text-slate-500 dark:text-slate-400">Folders</p>
              <div className="space-y-1">
                {folders.map(f => (
                  <button
                    key={f.id}
                    onClick={() => setSelectedFolder(f.id)}
                    className={`${sidebarItem} justify-between ${selectedFolder === f.id ? sidebarActive : sidebarIdle}`}
                  >
                    <span className="flex items-center gap-3 truncate">
                      <FolderIcon className="h-4 w-4" />
                      {f.name}
                    </span>
                    {f.bookmark_count ? (
                      <span className="text-xs tabular-nums text-slate-400 dark:text-slate-500">{f.bookmark_count}</span>
                    ) : null}
                  </button>
                ))}
              </div>
            </div>
          </aside>

          <div className="flex-1 space-y-8">
            <div>
              <p className="text-sm font-medium text-slate-500 dark:text-slate-400">Markly redesign mock</p>
              <h1 className="mt-1 max-w-3xl font-display text-4xl font-normal leading-tight text-slate-950 sm:text-5xl dark:text-slate-50">
                A quieter bookmark library, with a little serif flourish.
              </h1>
              <p className="mt-3 max-w-2xl text-base leading-7 text-slate-600 dark:text-slate-400">
                Slate palette, soft gradient surfaces, Instrument Serif on titles, Inter everywhere else.
                Indigo only appears on hover or active states.
              </p>
            </div>

            {/* TopicsBox */}
            <TopicsBox
              tags={topics}
              selectedTags={selectedTags}
              onTagClick={toggleTag}
              onClearFilters={() => setSelectedTags([])}
            />

            {/* Folder grid */}
            <div>
              <div className="mb-3 flex items-center justify-between">
                <h2 className="font-display text-xl text-slate-950 dark:text-slate-50">Folders</h2>
              </div>
              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">
                {folders.map(f => (
                  <FolderCard key={f.id} folder={f} onClick={() => undefined} />
                ))}
              </div>
            </div>

            {/* Bookmark grid */}
            <div>
              <div className="mb-3 flex items-center justify-between">
                <h2 className="font-display text-xl text-slate-950 dark:text-slate-50">Recent bookmarks</h2>
              </div>
              <div className="grid items-start gap-6 md:grid-cols-3">
                {bookmarks.map(b => (
                  <BookmarkCard key={b.id} bookmark={b} onTagClick={toggleTag} onVisibilityToggle={() => undefined} />
                ))}
              </div>
            </div>

            {/* List view */}
            <div>
              <div className="mb-3 flex items-center justify-between">
                <h2 className="font-display text-xl text-slate-950 dark:text-slate-50">List view</h2>
              </div>
              <div className="overflow-hidden rounded-card bg-surface-light shadow-card ring-1 ring-white/60 dark:bg-surface-dark dark:ring-white/10">
                {bookmarks.map(b => (
                  <BookmarkRow key={b.id} bookmark={b} onTagClick={toggleTag} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
